stages:
  - build

open-pull-request:
  stage: build
  image: ubuntu:20.04

  before_script:
    - apt-get update
    - apt-get -y install curl gpg
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - apt-get update
    - apt-get -y install gh
    - git config --global user.email ${CI_GITHUB_EMAIL}
    - git config --global user.name ${CI_GITHUB_USER}

    - gh auth login --with-token < ${CI_TOKEN_GITHUB_AUTH}
    - gh repo clone ${CI_GITHUB_DOCS_REPO} documentation
    - cd documentation
    - echo ${CI_COMMIT_MESSAGE}
    - git checkout -b cr-${CI_COMMIT_SHORT_SHA}

  script:
    - mkdir -p $PATH_DESTINATION api-reference
    - cp ${CI_API_REFERENCE_DIRECTORY}/*.yaml api-reference
    - git add .
    - git commit -m "${CI_COMMIT_MESSAGE}"
    - git remote set-url origin https://${CI_TOKEN_GITHUB}@github.com/${CI_GITHUB_DOCS_REPO}.git
    - git push -u origin HEAD
    - gh pr create --title "${CI_COMMIT_MESSAGE}" --body "${CI_COMMIT_AUTHOR}"

  only:
    refs:
      - main
      - master
    changes:
      - ${CI_PATH_CHANGE}*
      - dist/production/*
